#!/bin/bash

set -e

if [ $# -ne 2 ]; then
  echo "Usage: $0 <module_name> <module_path>"
  echo "Ex: $0 hashtable libs/hashtable"
  exit 1
fi

MODULE_NAME=$1
MODULE_PATH=$2

# Déduit la racine d'include à utiliser
if [[ "$MODULE_PATH" == libs/* ]]; then
  INCLUDE_LINES='
    ${ROOT_DIR}/libs
  '
elif [[ "$MODULE_PATH" == src/* ]]; then
  INCLUDE_LINES='
    ${ROOT_DIR}/src
    ${ROOT_DIR}/libs
  '
else
  echo "Erreur : le chemin doit commencer par libs/ ou src/"
  exit 1
fi

# Crée les dossiers
mkdir -p "$MODULE_PATH/src"
mkdir -p "$MODULE_PATH/include"
mkdir -p "$MODULE_PATH/cmake"
mkdir -p "$MODULE_PATH/tests"


# gen std_macros

sh "scripts/cmake/sh/gen_std_macros.sh" "$MODULE_PATH/cmake/std_macros.cmake" > /dev/null  || {
    echo "❌ Erreur lors de la génération de std_macros.cmake"
    exit 1
}

# gen toolchain


# Génère le CMakeLists.txt
cat > "$MODULE_PATH/CMakeLists.txt" <<EOF
# =============================================================================
# ⚠️  THIS FILE IS AUTO-GENERATED — DO NOT EDIT MANUALLY
# =============================================================================
# This file was generated by: scripts/cmake/sh/new_module.sh
#
# Manual modifications will be overwritten.
# If you need to make changes, please update the generator script
# or submit a pull request explaining your changes.
# =============================================================================


cmake_minimum_required(VERSION 3.28...4.0.2)
project(${MODULE_NAME} LANGUAGES C)

set(MODULE_STD_MACRO "\${CMAKE_CURRENT_SOURCE_DIR}/cmake/std_macros.cmake")
if(EXISTS \${MODULE_STD_MACRO})
    include(\${MODULE_STD_MACRO})
endif()

set(CMAKE_C_STANDARD 11)


get_filename_component(ROOT_DIR "\${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

if (NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "Ce projet requiert clang comme compilateur C.")
endif()

add_library(\${PROJECT_NAME} OBJECT)

file(GLOB_RECURSE SOURCE_FILES CONFIGURE_DEPENDS
    "\${CMAKE_CURRENT_LIST_DIR}/src/*.c"
)

target_sources(\${PROJECT_NAME} PRIVATE \${SOURCE_FILES})

target_include_directories(\${PROJECT_NAME}
    PRIVATE
    ${INCLUDE_LINES}
    "\${CMAKE_CURRENT_SOURCE_DIR}/include"
)

target_compile_options(\${PROJECT_NAME} PRIVATE
    -O1 -Wall -Wextra -Wpedantic -std=c11
    -Wshadow -Wcast-align -Wunused -Wold-style-definition
    -Wmissing-prototypes -Wno-unused-parameter -Werror
    -Wstrict-prototypes -Wpointer-arith -Wwrite-strings
    -Wconversion -Wformat=2 -Wformat-security
    -Wunreachable-code -Wundef -Wbad-function-cast
    -Wdouble-promotion -Wmissing-include-dirs
    -Winit-self -Wmissing-noreturn -fno-common
    -fstack-protector-strong -D_FORTIFY_SOURCE=2
)

set(MODULE_CONFIG "\${CMAKE_CURRENT_SOURCE_DIR}/cmake/config.cmake")
if(EXISTS \${MODULE_CONFIG})
    include(\${MODULE_CONFIG})
endif()

set_target_properties(\${PROJECT_NAME} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "\${CMAKE_CURRENT_BINARY_DIR}"
)

# =====================================================================================
# Testing part: compile module’s objects + tests only if BUILD_TESTING is ON
# =====================================================================================

option(BUILD_TESTING "Enable tests" OFF)

if(BUILD_TESTING)
    enable_testing()

    file(GLOB TEST_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.c")
    set(test_executable_name "test_${PROJECT_NAME}")

    add_executable(${test_executable_name}
        ${TEST_SOURCES}
        $<TARGET_OBJECTS:${PROJECT_NAME}>
    )

    target_include_directories(${test_executable_name}
        PRIVATE
            ${CMAKE_CURRENT_SOURCE_DIR}/include
            ${CMAKE_CURRENT_SOURCE_DIR}/tests
    )

    set_target_properties(${test_executable_name} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/bin/test"
    )

    add_test(
        NAME ${test_executable_name}
        COMMAND "${CMAKE_CURRENT_BINARY_DIR}/bin/test/${test_executable_name}"
    )
endif()

EOF

echo "✅ Module '${MODULE_NAME}' created at '${MODULE_PATH}'"