#!/bin/sh

OUT="$1"

cat <<'EOF' > "$OUT"
# =============================================================================
# ⚠️  THIS FILE IS AUTO-GENERATED — DO NOT EDIT MANUALLY
# =============================================================================
# This file was generated by: scripts/sh/cmake/gen_std_macros.sh
#
# Manual modifications will be overwritten.
# If you need to make changes, please update the generator script
# or submit a pull request explaining your changes.
# =============================================================================


# -----------------------------------------------------------------------------
# Usage example:
#
#   require_dependency(hashtable libs/hashtable)
#
# This will:
# - Add the subdirectory at the given path (with an isolated build dir)
# - Include "${dep_path}/include" as a private include directory
# - Link the current target (${PROJECT_NAME}) with the dependency target
# -----------------------------------------------------------------------------
function(require_dependency dep_name dep_path)
    # Construit le chemin absolu vers la dépendance
    # Ex: si dep_path = "libs/hashtable", alors dep_abs_path = "/chemin/vers/projet/libs/hashtable"
    # Build absolute path to the dependency
    # Ex: if dep_path = "libs/hashtable", then dep_abs_path = "/project/path/libs/hashtable"
    set(dep_abs_path "${ROOT_DIR}/${dep_path}")
    
    # Crée un répertoire de build isolé pour cette dépendance
    # Ceci évite les conflits si plusieurs modules utilisent la même dépendance
    # Ex: hashtable sera compilé dans "${CMAKE_BINARY_DIR}/_deps/hashtable-build"
    # Create isolated build directory for this dependency
    # This avoids conflicts if multiple modules use the same dependency
    # Ex: hashtable will be compiled in "${CMAKE_BINARY_DIR}/_deps/hashtable-build"
    set(dep_build_dir "${CMAKE_BINARY_DIR}/_deps/${dep_name}-build")
    
    # Ajoute le sous-répertoire de la dépendance au build
    # Ceci va automatiquement traiter le CMakeLists.txt de la dépendance
    # et créer la target "hashtable" (ou autre nom de dépendance)
    # Add dependency subdirectory to build
    # This will automatically process the dependency's CMakeLists.txt
    # and create the "hashtable" target (or other dependency name)
    add_subdirectory("${dep_abs_path}" "${dep_build_dir}")
    
    # Ajoute le répertoire include/ de la dépendance aux chemins de recherche du module courant
    # Add the dependency's include/ directory to current module's search paths
    #
    # Ceci permet d'utiliser #include <hashtable.h> directement dans le code
    # This allows using #include <hashtable.h> directly in code
    #
    # PRIVATE : Les headers de la dépendance sont visibles uniquement par ce module,
    #           pas par les modules qui dépendent de ce module
    # PRIVATE:  Dependency headers are visible only to this module,
    #           not to modules that depend on this module
    target_include_directories(${PROJECT_NAME} PRIVATE "${dep_abs_path}/include")
    
    # Lie la target courante avec la dépendance
    # Ceci assure que la dépendance sera compilée avant ce module
    # et que les symboles de la dépendance seront disponibles au link
    # Link current target with dependency
    # This ensures dependency will be compiled before this module
    # and dependency symbols will be available at link time
    target_link_libraries(${PROJECT_NAME} PRIVATE ${dep_name})
endfunction()



# -----------------------------------------------------------------------------
# Usage example:
#
#   require_test_dependency(test_utils libs/test_utils)
#
# This will:
# - Add the subdirectory at the given path (with an isolated build dir)
# - Include "${dep_path}/include" as a private include directory
# - Link the test executable with the dependency target
#
# ⚠️ This function only runs if BUILD_TESTING is enabled.
# -----------------------------------------------------------------------------
function(require_test_dependency dep_name dep_path)
    # Exit immediately if we're not in a testing build
    if(NOT BUILD_TESTING)
        return()
    endif()

    # Build absolute path to the dependency
    set(dep_abs_path "${ROOT_DIR}/${dep_path}")

    # Create an isolated build directory for this dependency
    set(dep_build_dir "${CMAKE_BINARY_DIR}/_deps/${dep_name}-build")

    # Add the dependency subdirectory (this creates the "${dep_name}" target)
    add_subdirectory("${dep_abs_path}" "${dep_build_dir}")

    # Add the include/ directory to the test executable
    target_include_directories(${test_executable_name} PRIVATE "${dep_abs_path}/include")

    # Link the test executable with the dependency
    target_link_libraries(${test_executable_name} PRIVATE ${dep_name})
endfunction()

# 😈
function(thank_you_linuxydable)
    message(STATUS "Thank you linuxydable 🐉")
endfunction()

EOF
